// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Aardvark.Base.TypeProviders")>]
[<assembly: AssemblyProductAttribute("Aardvark.Base.TypeProviders")>]
[<assembly: AssemblyDescriptionAttribute("Peano types")>]
[<assembly: AssemblyVersionAttribute("1.0.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Aardvark.Base.TypeProviders"
    let [<Literal>] AssemblyProduct = "Aardvark.Base.TypeProviders"
    let [<Literal>] AssemblyDescription = "Peano types"
    let [<Literal>] AssemblyVersion = "1.0.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0.0"